### ISSUE TITLE
CubeConfig for Sentinel-1 image 

### ISSUE THREAD

**Issue by shexiaogui** [dcs4cop/xcube-sh#10]
I read the [example notebook](https://github.com/dcs4cop/xcube-sh/blob/master/examples/notebooks/Ex1b-DCFS-Datasets.ipynb) of accessing Sentinel-1 image. Following questions:
- The spatial_res was set to be 0.00018, where did this number come from ? is this [m/pixel in this doc](https://docs.sentinel-hub.com/api/latest/#/data/Sentinel-1-GRD)

- the tile size 512x 512 was smaller than the original xarray dimension 2048x3072, how is the data being chunked or downsampled ? Given bbox, crs and spatial_res, the dimension of image should be more or less fixed, by specify the tile_size, which operation is done to the tile ? 

> <xarray.Dataset>
> Dimensions:    (bnds: 2, **lat: 2048, lon: 3072**, time: 40)
> Coordinates:
>     lat        (lat) float64 54.64 54.64 54.64 54.64 ... 54.27 54.27 54.27 54.27
>     lon        (lon) float64 10.0 10.0 10.0 10.0 ... 10.55 10.55 10.55 10.55
>     time       (time) datetime64[ns] 2019-05-15 2019-05-17 ... 2019-08-01
>     time_bnds  (time, bnds) datetime64[ns] dask.array<chunksize=(40, 2), meta=np.ndarray>
> Dimensions without coordinates: bnds
> Data variables:
>     VH         (time, lat, lon) float32 **dask.array<chunksize=(1, 512, 512**), meta=np.ndarray>

- On EDC I tried my self using a different config with more bands like the following. (Also tried HH, HV)
```
cube_config = CubeConfig(dataset_name='S1GRD',
                         band_names=[ 'HH+HV', 'VV+VH', 'HH', 'VV'], 
                         crs = "http://www.opengis.net/def/crs/EPSG/0/4326",
                         spatial_res = 0.00018,
                         geometry=bbox,
                         time_range=[start_date, end_date],
                         time_period='1D')
```
The cube returned contains those bands as variables but when I tried to access the values using `cube.HH.values`, it throws exception with
```
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/zarr/storage.py in __getitem__(self, key)
   1924             with self._mutex:
-> 1925                 value = self._values_cache[key]
   1926                 # cache hit if no KeyError is raised

KeyError: 'HH/4.0.0'
...... 

/opt/conda/lib/python3.7/site-packages/xcube_sh/sentinelhub.py in get_data(self, request, mime_type)
    246         else:
    247             # TODO (forman): return NaN/Zero chunk
--> 248             raise NotImplementedError('return NaN/Zero chunk')
```

The same happened at HH, HV, sometimes also VH

**Comment by forman** [comment]
@shexiaogui thanks for reporting.

> The spatial_res was set to be 0.00018, where did this number come from ? 

Spatial resolution is always in the units of the CRS. In this case, these are degrees. 

> the tile size 512x 512 was smaller than the original xarray dimension 2048x3072

Not understood as the tile size is always less or equal spatial dimensions. What is your issue here?

> it throws exception with

That shouldn't happen. I'll try to reproduce...

**Comment by shexiaogui** [comment]
Thank you very much for replying. Let me elaborate on my first two questions. 

- Regarding spatial resolution, I am not very familiar with SAR imagery and it looks like the spatial resolution for S1 and S2 are different. S2 images is 10m/pixel which means one pixel corresponds to 10m. What does the degree means ?

- You mean the tile size (512x512) is in pixel and the returned xarray dimension (2048x3072) is spatial dimension? What does the spatial dimension mean ? Again in Sentinel-2 product, if I set spatial res to be 10m/pixel and tile size to be 512x512, the returned xarray dimension will be 512x512. 

I have a feeling that these two questions are related, because I don't know how the resolution in degree is mapped to m/pixel.

**Comment by forman** [comment]
@shexiaogui sorry for the late reply! 

> What does the degree means ?

Degrees are only expected if the requested coordinate reference system is equi-rectangluar lon/lat "Projection", oftern referred to as EPSG:4326 or WGS84. Then you have `180 / PI / R)` degrees per meter (or `PI * R / 180` meters per degree), where PI=3.1415... and R=6378137m is the average radius of the WGS84 Earth's ellipsod. 

> You mean the tile size (512x512) is in pixel and the returned xarray dimension (2048x3072) is spatial dimension?

No, the units of tile size and xarray dimensions are both number of pixels.
