### ISSUE TITLE
Use SH Catalog API instead of WFS

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube-sh#14]
SENTINEL Hub now offers a Catalog API: https://docs.sentinel-hub.com/api/latest/api/catalog/ and API reference: https://docs.sentinel-hub.com/api/latest/reference/#tag/STAC

This means that we can avoid using WFS altogether and users do not need to set their instance id. 

- [x] Document changes
- [x] Inform related people from https://gitext.sinergise.com/dcfs/common/-/issues/203

**Comment by gunbra32** [comment]
User reported that sometiems xcube-sh request fail with error messages related to WFS usage: 

[related issue in DCFS repo](https://gitext.sinergise.com/dcfs/common/-/issues/223)

![grafik](https://user-images.githubusercontent.com/7138923/96882752-eaf10c00-147f-11eb-978c-375f1cd2d294.png)

**Comment by forman** [comment]
In 0.6.0
