### ISSUE TITLE
Clarification on SH user credentials in README

### ISSUE THREAD

**Issue by hfisser** [dcs4cop/xcube-sh#22]
Hi,

could you clarify in the README (or refer to another resource) the specific origin of:

SH_INSTANCE_ID=<your instance ID>    
SH_CLIENT_ID=<your client ID>    
SH_CLIENT_SECRET=<your client secret>

CLIENT_ID and CLIENT_SECRET are clear to me, INSTANCE_ID is not.
An explanation would help. Maybe also alignment with the denotations in the SH account settings.

Thanks & cheers! :)

**Comment by AliceBalfanz** [comment]
Hi, 
thanks for the message :)
Please note, that with xcube-sh version 0.6.0 release `instance_id` has been deprecated and only client_id and client_secret are needed. 
You can find an entry in the [Changelog](https://github.com/dcs4cop/xcube-sh/blob/master/CHANGES.md#changes-in-060):

> The keyword argument instance_id of the SentinelHub and SentinelHubStore constructors has been deprecated. It is no longer required

This issue can be therefore closed :)

Cheers!
