### ISSUE TITLE
Demo1-xcube-sh.ipynb: FileNotFoundError: Could not find file ../geodb/germany-sh-lakes.geojson

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-sh#36]
`xcube-sh/examples/notebooks/Demo1-xcube-sh.ipynb` in cell 29 an `FileNotFoundError` occurs:  `Could not find file ../geodb/germany-sh-lakes.geojson`
Please add the necessary data to the examples directory in order to ensure the execution of the whole notebook

![image](https://user-images.githubusercontent.com/23457217/105324442-b77f6400-5bcb-11eb-8da8-0af90e343a41.png)

**Comment by forman** [comment]
I'll delete that NB entirely. Its content is covered in other NBs.
