### ISSUE TITLE
move Ex4-DCFS-GeoDB.ipynb to xcube-geoDB

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-sh#37]
xcube-sh/examples/notebooks/Ex4-DCFS-GeoDB.ipynb is not working, there is even a information message about that in the notebook itself: 

![image](https://user-images.githubusercontent.com/23457217/105325137-8e130800-5bcc-11eb-98b4-a8ec5b3146fa.png)

Please take care of moving it, where it belongs :) Thanks a lot

**Comment by AliceBalfanz** [comment]
Or maybe do we need to delete the NB all together?

**Comment by forman** [comment]
The Notebook should remain there but be updated soon to use the actual `xcube-geodb` package. Meanwhile I placed a warning banner at its top.

Closing this in favour of #401

**Comment by forman** [comment]
> Please take care of moving it, where it belongs :) Thanks a lot

Please read the NB banner carefully :)
