### ISSUE TITLE
Wrong label when plotting cube

### ISSUE THREAD

**Issue by maximlamare** [dcs4cop/xcube-sh#50]
When plotting an Xcube (for example following the standard example notebooks in the Euro Data Cube Marketplace), the `y` label is wrongly set as `longitude` rather than `latitude`.

![Screenshot from 2021-03-09 11-28-53](https://user-images.githubusercontent.com/32132761/110457569-112fe500-80cb-11eb-9024-a33506561de8.png)

**Comment by forman** [comment]
Should be fixed in 0.7.0 by https://github.com/dcs4cop/xcube-sh/pull/32
