### ISSUE TITLE
Wrong dates for S2 in xcube-sh

### ISSUE THREAD

**Issue by maximlamare** [dcs4cop/xcube-sh#60]
Maybe my approach is flawed, but `xcube-sh` seems to return wrong dates for Sentinel-2:

```py
cube_config = CubeConfig(dataset_name='S2L2A',
                         band_names=['B03', 'B08', 'CLM'],
                         bbox=bounding_box_buffered.envelope.bounds,
                         crs=f"http://www.opengis.net/def/crs/EPSG/0/3857",
                         spatial_res=10,
                         time_range=['2020-06-01', '2020-06-30'],                         
                         )  
```

returns the following dates (which are incorrect, see last step in this issue):

```py
array(['2020-06-03T06:32:14.000000000', '2020-06-08T06:32:18.000000000',
       '2020-06-13T06:32:14.000000000', '2020-06-18T06:32:18.000000000',
       '2020-06-23T06:32:15.000000000', '2020-06-28T06:32:17.000000000'],
      dtype='datetime64[ns]')
```

I was puzzled that this cube was full of `nans` so I ran:

```py
cube_config = CubeConfig(dataset_name='S2L2A',
                         band_names=['B03', 'B08', 'CLM'],
                         bbox=bounding_box_buffered.envelope.bounds,
                         crs=f"http://www.opengis.net/def/crs/EPSG/0/3857",
                         spatial_res=10,
                         time_range=['2020-06-01', '2020-06-30'],
                         time_period="1D"
                         )  
```

which then obviously returns all days. Therefore I added the following command when opening the cube:

```py
s2_cube = open_cube(cube_config)

# Drop empty time slices
s2_cube = s2_cube.dropna(dim="time")
```

which returns the correct dates (but after almost a minute of processing!)

```py
array(['2020-06-01T12:00:00.000000000', '2020-06-04T12:00:00.000000000',
       '2020-06-06T12:00:00.000000000', '2020-06-09T12:00:00.000000000',
       '2020-06-11T12:00:00.000000000', '2020-06-14T12:00:00.000000000',
       '2020-06-16T12:00:00.000000000', '2020-06-19T12:00:00.000000000',
       '2020-06-21T12:00:00.000000000', '2020-06-24T12:00:00.000000000',
       '2020-06-26T12:00:00.000000000', '2020-06-29T12:00:00.000000000'],
      dtype='datetime64[ns]')
```

As you can see these correct dates are different from those returned by the first step.

**Comment by AliceBalfanz** [comment]
Hi Maxim, could you provide the bounding box you are using? This would be great :)

**Comment by maximlamare** [comment]
@AliceBalfanz with pleasure:

`(2894267.8988124575, 9262943.968658403, 2899443.8488556934, 9268505.554239485)` in EPSG 3857 ( `crs=f"http://www.opengis.net/def/crs/EPSG/0/3857"`)

**Comment by AliceBalfanz** [comment]
There is an issue with swapped coordinates when changing the crs from EPSG:3857 to EPSG:4326, need to clean up my notebook and will document here next week.

**Comment by AliceBalfanz** [comment]
https://github.com/dcs4cop/xcube-sh/blob/e8de4194ac55863fe6f61e0dc1e2fe3fc96d8cdf/xcube_sh/sentinelhub.py#L187

After further investigations the above line caused the trouble, as it expects the same order of x and y in both sources and target crs. However, in terms of x and y WGS84 is swapped, meaning (y/x): 

https://www.w3.org/2015/spatial/wiki/Coordinate_Reference_Systems#EPSG_database

Here you can see the mapped bounding boxes from the investigation, at the very end you can find the whole notebook attached

First, the original bbox with the source CRS as provided by Maxim:
![image](https://user-images.githubusercontent.com/23457217/126965709-9d98668a-5bbd-43e3-abaa-70266d784bf9.png)


![image](https://user-images.githubusercontent.com/23457217/126965771-b6e86b54-3ae6-42c5-8b45-fe796dd2bde0.png)

![image](https://user-images.githubusercontent.com/23457217/126965806-66d9c631-323e-4df1-b5e7-fcf255a6617b.png)

[Investigate_xcube-sh_issue60.pdf](https://github.com/dcs4cop/xcube-sh/files/6877110/Investigate_xcube-sh_issue60.pdf)
