### ISSUE TITLE
Incorrectly set of timestamps in Seasonal Trajectories, 10-daily & Vegetation Phenology and Productivity Parameters Season 1&2, Yearly collection

### ISSUE THREAD

**Issue by bontekasper** [dcs4cop/xcube-sh#75]
When requesting the ST PPI  from HR-VPP (see https://collections.eurodatacube.com/seasonal-trajectories/)  as follows:

cube_config = CubeConfig(dataset_name='CUSTOM',
                         band_names=['myband'],
                         bbox=aoi_coords,
                         crs = projection_code,
                         time_range=['2018-07-01', '2019-12-31'],
                         time_period="10d",
                         spatial_res=spatial_res,
                         band_sample_types='FLOAT32',
                         collection_id=my_collection_id
                         )
my_cube = open_cube(cube_config)

The timestamps are not correctly set and do not follow the decadal structure of the HR-VPP data (1,11 or 21st of the month).  
It seems that in the EDC collection always add 10 days from the first observation instead of using always the dekadal structure.  Below you can find a snipped of the ST timestamps: 
![image](https://user-images.githubusercontent.com/60655533/140726362-14cf28b4-a3a5-487c-a9a2-8a82c1455176.png)

Furthermore, if I request the ST PPI dataset for a daily time period and afterwards filter out the empty time stamps, still twice as much timestamps are returned compared to what is expected within the HR-VPP product. 

A similar issue occurs when requesting the yearly VPP collection. The timestamps are incorrectly set within xcube, meaning that for the 1st January, the data is also duplicated on the 31st December of the previous year. Therefore, with the "1Y" parameter you are aggregating 2018 (01.01) and 2019 (31.12) data together which is far from ideal.

**Comment by forman** [comment]
This issue is similar if not equal to #35 and #67.

**Comment by bontekasper** [comment]
One note to add here: the timestamps that are filled, contains invalid data probably due to mixing of different time period together. Like for example in the VPP case, the timestamp of 2017 is merged together with 2018 data. This is potentially a difference compared to issue #67

**Comment by forman** [comment]
I hope this is an artifact of (currently) being forced to pass a value for the `time_period` parameter. In the new implementation, if `time_period = None`, timestamps are the ones directly retrieved from datasets.

**Comment by forman** [comment]
Closed by #74 after review with @bontekasper
