### ISSUE TITLE
Building Sentinel-2 antimeridian cube fails

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-sh#84]
When requesting a sentinel-2 cube with xcube gen2 in an area crossing the antimeridian, it fails with   
`Failed to detect grid mapping: cannot find any grid mapping in dataset`

To reproduce, use the follwoing xcube gen configuration: 
https://github.com/bcdev/service-eurodatacube/blob/master/test-procedures/test-stores/request_cube_configs/request-sh-antimeridian_S2L2A_B04_B05.yml

**Comment by forman** [comment]
Why do you think this is an `xcube-sh` issue?

**Comment by forman** [comment]
Btw, the link you provided is internal. Please provide a minimal example with only `xcube-sh` code.

**Comment by AliceBalfanz** [comment]
closing, because I move the issue to xcube issue tracker: https://github.com/dcs4cop/xcube/issues/682
